global:
  scrape_interval: 15s

scrape_configs:
  # Application Spring Boot
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['student-management-jenkins:8089']

  # Jenkins Metrics
  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'jenkins'

  # Node Exporter (Ubuntu)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker Containers
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
